### ISSUE TITLE
Tente 3D support links

### ISSUE THREAD

**Issue by cpcbegin** [adius/awesome-lego#19]
LDraw is an open format than allow to use with other construction system as TENTE or Exin Castilos, here you are more interesting links:

- [Script linux to install several LDraw utils in Ubuntu family GNU/Linux distros for use with LEGO, TENTE or Exin Castillos](https://gitlab.com/cpcbegin/retromultiinstaller).
- [Tente 3D set of pieces](https://www.dropbox.com/s/9ylx1tparps72ta/LDrawTente_Ultima.zip?dl=1).
- [Tente 3D example models](https://github.com/cpcbegin/tentemodels)
- [Tente 3D wiki (on English)](https://3dtente.fandom.com/wiki/Main_Page).
- [Tente 3D wiki (on Spanish, much more complete)](https://tente3d.fandom.com/es/wiki/Tente_3D_Wiki).
- [Exin castillos set of pieces (on Spanish and required sign in)](https://exincastillos.es/foro/download/file.php?id=284).

**Comment by ad-si** [comment]
Seems to be to old and deprecated to be relevant.

**Comment by cpcbegin** [comment]
All this info keep updated and on-line.

**Comment by ad-si** [comment]
The first link is an installer. How's that relevant?
None of the other linked resources had recent activity.
